name: Link Check

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1" # Once a week

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Restore lychee cache
        uses: actions/cache@v6
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Check Markdown links with lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --cache --max-cache-age 1d './**/*.md'
